name = "MarineHeatwaves"
uuid = "de38a2fb-735b-4df9-8733-90a2e2665a44"
authors = ["keduba <jfk.uba@pm.me>, Manal Elawady <mh.elawady@uliege.be> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
